from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from app.services.tracking.models import BoundingBox

class EventType(str, Enum):
    TRACK_STARTED = "TRACK_STARTED"
    TRACK_ENDED = "TRACK_ENDED"
    ZONE_ENTRY = "ZONE_ENTRY"
    ZONE_EXIT = "ZONE_EXIT"
    LOITERING = "LOITERING"
    RAPID_MOVEMENT = "RAPID_MOVEMENT"
    DIRECTION_CHANGE = "DIRECTION_CHANGE"
    MULTIPLE_OBJECT_PROXIMITY = "MULTIPLE_OBJECT_PROXIMITY"

class Event(BaseModel):
    """
    Represents an observable behavioral event generated by the Event Intelligence system.
    """
    event_id: str = Field(..., description="Unique identifier for the event")
    event_type: EventType = Field(..., description="The type of the event")
    frame_number: int = Field(..., description="The video frame number where the event occurred or concluded")
    timestamp_seconds: float = Field(..., description="The exact temporal timestamp of the event in seconds")
    description: str = Field(..., description="A human-readable explanation of the event based purely on observable behavior")
    
    # Optional fields for event-specific data
    track_id: Optional[int] = Field(None, description="The primary tracked object associated with this event, if applicable")
    
    # Structured evidence to support explainability
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Structured key-value metrics explaining what caused the event")

class TrackObservation(BaseModel):
    """
    Represents a single temporal observation of a tracked object.
    Used for maintaining historical state.
    """
    track_id: int = Field(..., description="The unique identifier of the tracked object")
    frame_number: int = Field(..., description="The sequence frame number of this observation")
    timestamp_seconds: float = Field(..., description="The temporal timestamp in seconds")
    bounding_box: BoundingBox = Field(..., description="The spatial bounding box of the object")
    class_id: int = Field(..., description="The detected class ID")
    class_name: str = Field(..., description="The detected class name")
    confidence: float = Field(..., description="The detection or tracking confidence")

