import os
from pathlib import Path
import pytest
from sqlalchemy import create_engine, inspect
from unittest.mock import patch
from alembic.config import Config
from alembic import command
from alembic.script import ScriptDirectory

from app.core.config import get_settings


# Path to the backend directory, where alembic.ini is located
BACKEND_DIR = Path(__file__).parent.parent
ALEMBIC_INI_PATH = BACKEND_DIR / "alembic.ini"


@pytest.fixture(scope="session")
def alembic_config():
    """Provides a configured Alembic Config object."""
    config = Config(str(ALEMBIC_INI_PATH))
    # We must set the script_location relative to the backend directory
    # since we are running tests from the project root usually.
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    return config


def test_alembic_configuration_is_loadable(alembic_config):
    """Ensure alembic.ini is loadable and paths are correct."""
    script = ScriptDirectory.from_config(alembic_config)
    assert script is not None
    
    # Ensure at least one revision exists (the initial schema)
    revisions = list(script.walk_revisions())
    assert len(revisions) > 0, "No alembic revisions found. Initial migration is missing."


def test_env_py_does_not_hardcode_credentials(alembic_config):
    """Ensure env.py doesn't have hardcoded URLs but instead uses settings."""
    env_py_path = BACKEND_DIR / "alembic" / "env.py"
    with open(env_py_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    assert "postgresql+psycopg://" not in content, "Hardcoded credentials found in env.py"
    assert "get_settings()" in content, "env.py does not use get_settings() for database URL"


def test_migration_upgrade_downgrade(alembic_config):
    """
    Test that migrations can apply and rollback cleanly.
    We use an isolated SQLite in-memory database to test the DDL generation safely
    without risking the main development database.
    Note: SQLite has dialect differences, but Alembic can still often run the downgrade/upgrade.
    However, due to Postgres-specific types (JSONB, ENUM), SQLite might fail. 
    Instead, we just test that the Alembic upgrade/downgrade functions exist and are discoverable.
    """
    script = ScriptDirectory.from_config(alembic_config)
    revisions = list(script.walk_revisions())
    
    head = revisions[0]
    
    # Ensure upgrade and downgrade functions exist in the migration module
    assert hasattr(head.module, "upgrade")
    assert hasattr(head.module, "downgrade")
    
    # Ensure the revision has an autogenerated message and ID
    assert head.revision is not None
    assert head.down_revision is None or isinstance(head.down_revision, str)
    assert any("schema" in rev.doc.lower() for rev in revisions if rev.doc)


def test_alembic_target_metadata_configured():
    """Ensure target_metadata correctly references the application's Base metadata."""
    env_py_path = BACKEND_DIR / "alembic" / "env.py"
    with open(env_py_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    assert "target_metadata = Base.metadata" in content


def test_alembic_upgrade_downgrade_execution(alembic_config, monkeypatch):
    """
    Test running the actual Alembic upgrade and downgrade against a disposable database.
    This ensures the generated migration SQL is completely valid for PostgreSQL.
    """
    test_db_url = "postgresql+psycopg://hawkeye:hawkeye@localhost:5432/hawkeye_test"
    
    # We patch the environment variable so get_settings() returns our test DB
    with patch.dict(os.environ, {"DATABASE_URL": test_db_url}):
        # Need to ensure that Settings picks it up if it's evaluated inside env.py
        # Actually env.py calls get_settings(), which is cached by lru_cache!
        # So we clear the cache for testing.
        from app.core.config import get_settings
        from app.db.models import Base
        from sqlalchemy import create_engine
        get_settings.cache_clear()
        
        # Clean up any dangling schema from crashed tests before upgrading
        eng = create_engine(test_db_url)
        Base.metadata.drop_all(eng)
        eng.dispose()
        
        script = ScriptDirectory.from_config(alembic_config)
        revisions = list(script.walk_revisions())
        assert len(revisions) > 0
        
        # Upgrade to head
        command.upgrade(alembic_config, "head")
        
        # Verify tables exist in test db
        engine = create_engine(test_db_url)
        inspector = inspect(engine)
        tables = inspector.get_table_names()
        assert "processing_sessions" in tables
        assert "evidence" in tables
        
        # Downgrade to base
        command.downgrade(alembic_config, "base")
        
        # Verify tables are removed
        inspector = inspect(engine)
        tables = inspector.get_table_names()
        assert "processing_sessions" not in tables
        assert "evidence" not in tables

