import pytest
from datetime import datetime, timezone

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from app.db.models import Base
from app.repositories.domain import ProcessingSessionDomain, TrackDomain
from app.services.events.models import Event as DomainEvent, EventType
from app.services.risk.models import RiskAssessment as DomainRiskAssessment, RiskLevel, Priority, RiskAssessmentStatus
from app.services.evidence.models import Evidence, EvidenceType, EvidenceSource, FrameEvidence, VideoSegmentEvidence

from app.repositories.sql_repo import (
    SQLProcessingSessionRepository,
    SQLTrackRepository,
    SQLEventRepository,
    SQLRiskAssessmentRepository,
    SQLEvidenceRepository
)
from app.services.evidence.lifecycle import EvidenceLifecycleService

from app.services.persistence.core import CorePersistenceService
from app.services.persistence.evidence import EvidencePersistenceService
from app.services.persistence.orchestrator import ProcessingPersistenceOrchestrator
from app.services.persistence.history import HistoryService, HistoricalProcessingRun

TEST_DB_URL = "postgresql+psycopg://hawkeye:hawkeye@localhost:5432/hawkeye_test"

@pytest.fixture(scope="module")
def engine():
    eng = create_engine(TEST_DB_URL)
    Base.metadata.drop_all(eng)
    with eng.connect() as conn:
        conn.execute(text("DROP TYPE IF EXISTS risklevel CASCADE"))
        conn.execute(text("DROP TYPE IF EXISTS priority CASCADE"))
        conn.execute(text("DROP TYPE IF EXISTS riskassessmentstatus CASCADE"))
        conn.execute(text("DROP TYPE IF EXISTS eventtype CASCADE"))
        conn.execute(text("DROP TYPE IF EXISTS evidencetype CASCADE"))
        conn.commit()
    Base.metadata.create_all(eng)
    yield eng
    Base.metadata.drop_all(eng)


@pytest.fixture
def db_session(engine):
    SessionLocal = sessionmaker(bind=engine)
    session = SessionLocal()
    yield session
    session.rollback()
    session.close()


@pytest.fixture
def persistence_setup(db_session):
    core = CorePersistenceService(
        session_repo=SQLProcessingSessionRepository(db_session),
        track_repo=SQLTrackRepository(db_session),
        event_repo=SQLEventRepository(db_session),
        risk_repo=SQLRiskAssessmentRepository(db_session)
    )
    evidence = EvidencePersistenceService(
        evidence_repo=SQLEvidenceRepository(db_session),
        lifecycle_service=EvidenceLifecycleService()
    )
    orchestrator = ProcessingPersistenceOrchestrator(core, evidence)
    history = HistoryService(core, evidence)
    return {
        "core": core,
        "evidence": evidence,
        "orchestrator": orchestrator,
        "history": history
    }


def test_complete_processing_run(persistence_setup, db_session):
    orchestrator = persistence_setup["orchestrator"]
    history = persistence_setup["history"]

    session_id = "orch_session_1"
    
    # Start Session
    session = orchestrator.start_session(session_id, "cam_1", "RTSP")
    assert session.status == "STARTED"
    
    # Mocking outputs generated by pipeline
    track = TrackDomain(id="track_1", processing_session_id=session_id, session_track_id=1, class_name="person")
    event = DomainEvent(event_id="evt_1", event_type=EventType.LOITERING, frame_number=10, timestamp_seconds=1.0, description="desc", track_id=None)
    risk = DomainRiskAssessment(
        event_id="risk_1",
        contributing_event_ids=["evt_1"],
        contributing_event_types=[EventType.LOITERING],
        risk_level=RiskLevel.HIGH,
        priority=Priority.HIGH,
        reason="desc",
        status=RiskAssessmentStatus.OPEN
    )
    evidence = Evidence(
        evidence_id="ev_1",
        evidence_type=EvidenceType.FRAME,
        source=EvidenceSource(source_id="cam_1", source_type="RTSP"),
        frame=FrameEvidence(frame_number=10, timestamp_seconds=1.0),
        event_id="evt_1"
    )
    
    # Complete session
    orchestrator.complete_session(
        session=session,
        tracks=[track],
        observations=[],
        events=[event],
        risk_assessments=[risk],
        evidence=[evidence]
    )
    
    # Caller commits the transaction
    db_session.commit()
    
    # Retrieve via history service
    historical_run = history.get_historical_run(session_id)
    
    assert historical_run.session.status == "COMPLETED"
    assert historical_run.session.completed_at is not None
    
    assert len(historical_run.tracks) == 1
    assert historical_run.tracks[0].id == "track_1"
    
    assert len(historical_run.events) == 1
    assert historical_run.events[0].event_id == "evt_1"
    
    assert len(historical_run.risk_assessments) == 1
    assert historical_run.risk_assessments[0].event_id == "risk_1"
    assert "evt_1" in historical_run.risk_assessments[0].contributing_event_ids
    
    assert len(historical_run.evidence) == 1
    assert historical_run.evidence[0].evidence_id == "ev_1"


def test_failed_processing_run(persistence_setup, db_session):
    orchestrator = persistence_setup["orchestrator"]
    history = persistence_setup["history"]

    session_id = "orch_session_fail"
    session = orchestrator.start_session(session_id, "cam_1", "RTSP")
    
    # Simulate processing failure before outputs
    orchestrator.fail_session(session)
    db_session.commit()
    
    historical_run = history.get_historical_run(session_id)
    assert historical_run.session.status == "FAILED"
    assert historical_run.session.completed_at is not None
    assert len(historical_run.tracks) == 0


def test_transaction_rollback_on_partial_failure(persistence_setup, db_session):
    orchestrator = persistence_setup["orchestrator"]
    history = persistence_setup["history"]

    session_id = "orch_session_partial"
    session = orchestrator.start_session(session_id, "cam_1", "RTSP")
    db_session.commit() # Save the session first for isolation check
    
    # Outputs with invalid reference to trigger an IntegrityError
    track = TrackDomain(id="track_invalid", processing_session_id="nonexistent_session", session_track_id=1, class_name="person")
    risk = DomainRiskAssessment(
        event_id="risk_invalid",
        contributing_event_ids=[],
        contributing_event_types=[],
        risk_level=RiskLevel.HIGH,
        priority=Priority.HIGH,
        reason="desc",
        status=RiskAssessmentStatus.OPEN
    )
    
    # Complete session will raise IntegrityError -> DuplicateRecordError on flush/commit
    with pytest.raises(Exception):
        orchestrator.complete_session(
            session=session,
            tracks=[track],
            events=[],
            risk_assessments=[risk],
            evidence=[]
        )
        db_session.flush()
    
    # We rollback the entire uncommitted transaction
    db_session.rollback()
    
    # Historical retrieval should only show the started session with NO tracks/risk
    historical_run = history.get_historical_run(session_id)
    assert len(historical_run.tracks) == 0
    assert len(historical_run.risk_assessments) == 0


def test_no_raw_media_in_historical_evidence(persistence_setup, db_session):
    orchestrator = persistence_setup["orchestrator"]
    history = persistence_setup["history"]

    session_id = "orch_session_media"
    session = orchestrator.start_session(session_id, "cam_1", "RTSP")
    
    evidence = Evidence(
        evidence_id="ev_media",
        evidence_type=EvidenceType.FRAME,
        source=EvidenceSource(source_id="cam_1", source_type="RTSP"),
        frame=FrameEvidence(frame_number=10, timestamp_seconds=1.0),
        event_id="dummy_event"
    )
    event = DomainEvent(
        event_id="dummy_event",
        event_type=EventType.LOITERING,
        frame_number=10,
        timestamp_seconds=1.0,
        description="desc"
    )
    
    orchestrator.complete_session(session, [], [], [event], [], [evidence])
    db_session.commit()
    
    historical_run = history.get_historical_run(session_id)
    retrieved_ev = historical_run.evidence[0]
    
    assert not hasattr(retrieved_ev, "image_bytes")
    assert not hasattr(retrieved_ev, "video_bytes")
