"""add_restricted_zone_to_schema

Revision ID: 78da1a0155cc
Revises: 99ac12bde0d4
Create Date: 2026-09-13 02:58:57.123702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78da1a0155cc'
down_revision: Union[str, Sequence[str], None] = '99ac12bde0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_sessions', sa.Column('restricted_zone', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_sessions', 'restricted_zone')
    # ### end Alembic commands ###
