"""add_track_observations_table to schema

Revision ID: 99ac12bde0d4
Revises: f057cb1ae518
Create Date: 2026-09-13 01:16:05.895313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ac12bde0d4'
down_revision: Union[str, Sequence[str], None] = 'f057cb1ae518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processing_session_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_observations_frame_number'), 'track_observations', ['frame_number'], unique=False)
    op.create_index(op.f('ix_track_observations_processing_session_id'), 'track_observations', ['processing_session_id'], unique=False)
    op.create_index(op.f('ix_track_observations_timestamp_seconds'), 'track_observations', ['timestamp_seconds'], unique=False)
    op.create_index(op.f('ix_track_observations_track_id'), 'track_observations', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_observations_track_id'), table_name='track_observations')
    op.drop_index(op.f('ix_track_observations_timestamp_seconds'), table_name='track_observations')
    op.drop_index(op.f('ix_track_observations_processing_session_id'), table_name='track_observations')
    op.drop_index(op.f('ix_track_observations_frame_number'), table_name='track_observations')
    op.drop_table('track_observations')
    # ### end Alembic commands ###
