"""add_processed_until_cursors

Revision ID: ca68f273194b
Revises: 78da1a0155cc
Create Date: 2026-09-13 09:00:55.404068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca68f273194b'
down_revision: Union[str, Sequence[str], None] = '78da1a0155cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_sessions', sa.Column('processed_until_frame', sa.Integer(), nullable=True))
    op.add_column('processing_sessions', sa.Column('processed_until_timestamp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_sessions', 'processed_until_timestamp')
    op.drop_column('processing_sessions', 'processed_until_frame')
    # ### end Alembic commands ###
