"""Initial schema

Revision ID: f057cb1ae518
Revises: 
Create Date: 2026-09-12 11:00:22.965236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f057cb1ae518'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('processing_session_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='riskassessmentstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_risk_assessments_processing_session_id'), 'risk_assessments', ['processing_session_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processing_session_id', sa.String(), nullable=False),
    sa.Column('session_track_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latest_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_processing_session_id'), 'tracks', ['processing_session_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('processing_session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('TRACK_STARTED', 'TRACK_ENDED', 'ZONE_ENTRY', 'ZONE_EXIT', 'LOITERING', 'RAPID_MOVEMENT', 'DIRECTION_CHANGE', 'MULTIPLE_OBJECT_PROXIMITY', name='eventtype'), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_processing_session_id'), 'events', ['processing_session_id'], unique=False)
    op.create_index(op.f('ix_events_track_id'), 'events', ['track_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('processing_session_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.Enum('FRAME', 'VIDEO_SEGMENT', name='evidencetype'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('frame_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_assessment_id'), 'evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_evidence_event_id'), 'evidence', ['event_id'], unique=False)
    op.create_index(op.f('ix_evidence_processing_session_id'), 'evidence', ['processing_session_id'], unique=False)
    op.create_table('risk_assessment_events',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessment_events')
    op.drop_index(op.f('ix_evidence_processing_session_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_event_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_assessment_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_events_track_id'), table_name='events')
    op.drop_index(op.f('ix_events_processing_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_tracks_processing_session_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_risk_assessments_processing_session_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('processing_sessions')
    
    # Drop custom ENUM types that are left behind in PostgreSQL
    op.execute("DROP TYPE IF EXISTS risklevel")
    op.execute("DROP TYPE IF EXISTS priority")
    op.execute("DROP TYPE IF EXISTS riskassessmentstatus")
    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS evidencetype")
    # ### end Alembic commands ###
